name: deploy (dev)

on:
  push:
    branches: [main]

jobs:
  deploy-core:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - run: ./deploy.sh dev
        env:
          AWS_REGION: ${{ vars.DEFAULT_DO_TERRAFORM_STATE_REGION }}
          AWS_ENDPOINT_URL_S3: ${{ vars.DEFAULT_DO_TERRAFORM_STATE_ENDPOINT_URL_S3 }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          CERT_MANAGER_ACME_EMAIL: ${{ vars.CERT_MANAGER_ACME_EMAIL }}
          EXTERNAL_DNS_TOKEN: ${{ secrets.EXTERNAL_DNS_TOKEN }}

  deploy-services:
    runs-on: ubuntu-latest
    environment: dev
    needs: deploy-core

    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 runtime-dev
      - run: ./deploy.sh
        working-directory: ./add-ons/services
        env:
          RUNTIME_DOMAIN: ${{ vars.RUNTIME_DEV_DOMAIN }}
          WEB_ANALYTICS_SECRET: ${{ secrets.WEB_ANALYTICS_SECRET }}
          WEB_ANALYTICS_POSTGRES_PASSWORD: ${{ secrets.WEB_ANALYTICS_POSTGRES_PASSWORD }}
          OBSERVE_ROOT_USER_EMAIL: ${{ vars.OBSERVE_ROOT_USER_EMAIL }}
          OBSERVE_ROOT_USER_PASSWORD: ${{ secrets.OBSERVE_ROOT_USER_PASSWORD }}
